---
- hosts: 
  - ceph_mon
  - ceph_osd

  remote_user: root

  tasks:
  - name: Get repo files
    get_url: url=http://172.27.1.1/repofiles/{{ item }} dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - rhel-7-server-rpms.repo
    - rhel-7-server-extras-rpms.repo
    - rhel-7-server-supplementary-rpms.repo
    - rhel-7-server-optional-rpms.repo
    - rhel-server-rhscl-7-rpms.repo
    - rhel-7-server-rh-common-rpms.repo
    - rhel-7-server-rhceph-2-tools-rpms.repo
    - rhel-7-server-rhceph-2-mon-rpms.repo
    - rhel-7-server-rhceph-2-osd-rpms.repo

  - name: Update
    yum: name=* state=latest

  - name: Delete machine-id
    file: path=/etc/machine-id state=absent

  - name: Create individual machine-id
    shell: systemd-machine-id-setup

- hosts: rhsc
  remote_user: root

  tasks:
  - name: Get repo files
    get_url: url=http://172.27.1.1/repofiles/{{ item }} dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - rhel-7-server-rhscon-2-agent-rpms.repo
    - rhel-7-server-rhscon-2-installer-rpms.repo
    - rhel-7-server-rhscon-2-main-rpms.repo

  - name: Install RHSC2
    yum: name={{ item }} state=latest
    with_items:
    - rhscon-core
    - rhscon-ceph
    - rhscon-ui

#Next Step: Auto-Install RHSC2 like: shell: skyring-setup --answer-file
#Next Step: hosts: osd & mon, shell exec RHSC2 agent install
#

