---
- hosts: localhost
  gather_facts: False
  vars_files:
  - vars/all.yml

  tasks:
  - name: Create Hostfile for L2
    file: path=rhepds_hosts state=touch

  - name: Add Hosts to Hostfile
    shell: echo "{{ vmnet.net }}.{{ item.value.id }}  {{ item.key }}.{{ vmnet.domain }} {{ item.key }}" >> rhepds_hosts
    with_dict: "{{ vms }}"
