---
- hosts: localhost
  gather_facts: False
  vars_files:
          # - vars/all.yml
  - vars/ast.yml

  tasks:

  - name: Delete VMs
    virt: name={{ item.key }}
          command=destroy
    with_dict: "{{ vms }}"

  - name: undefine VMs
    virt: name={{ item.key }}
          command=undefine
    with_dict: "{{ vms }}"

  - name: remove VM Disks
    file: path={{ vmdir }}{{ item.key }}.qcow2 state=absent
    with_dict: "{{ vms }}"

  - name: remove 2nd Disks
    file: path={{ vmdir }}{{ item.key }}_addisk.qcow2 state=absent
    when: item.value.addisk is defined
    with_dict: "{{ vms }}"

  - name: remove 3rd Disks
    file: path={{ vmdir }}{{ item.key }}_third.qcow2 state=absent
    when: item.value.third is defined
    with_dict: "{{ vms }}"
