---
- hosts: localhost
  gather_facts: False
  vars_files:
  - vars/ceph.yml

  tasks:

  - name: Delete VMs
    virt: name={{ item.key }}
          command=destroy
    with_dict: "{{ vms }}"

  - name: undefine VMs
    virt: name={{ item.key }}
          command=undefine
    with_dict: "{{ vms }}"

  - name: remove VM Disks
    file: path={{ vmdir }}{{ item.key }}.qcow2 state=absent
    with_dict: "{{ vms }}"

  - name: remove Additional Disks
    file: path={{ diskdir }}{{ item.key }}_addisk.qcow2 state=absent
    when: item.value.addisk is defined
    with_dict: "{{ vms }}"
