---
- hosts: localhost
  gather_facts: False
  vars_files:
  - vars/all.yml

  tasks:
  - name: create SSH-Keys
    shell: ssh-keygen -C root@"{{ item.key }}" -t rsa -N '' -f keys/"{{ item.key }}".key
    with_dict: "{{ vms }}"
