---
- hosts: all
  gather_facts: False

  tasks:
  - name : Subscribe Basics
    get_url: url=http://172.27.1.1/repofiles/{{ item }} dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - rhel-7-server-rpms.repo
    - rhel-7-server-extras-rpms.repo
    - rhel-7-server-supplementary-rpms.repo
    - rhel-7-server-optional-rpms.repo
    - rhel-server-rhscl-7-rpms.repo
    - rhel-7-server-rh-common-rpms.repo

  - name: create SSH-Keys
    shell: ssh-keygen -C root@"{{ item.key }}" -t rsa -N '' -f keys/"{{ item.key }}".key
    with_dict: "{{ vms }}"

  - name: create Autorized Keys
    shell: cat keys/"{{ item.key }}".key.pub >> keys/autorized.keys
    with_dict: "{{ vms }}"

- hosts: ose_all
  gather_facts: False

  tasks:
  - name : Subscribe Opensshift
    get_url: url=http://172.27.1.1/repofiles/{{ item }} dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - rhel-7-server-ose-3.1-rpms.repo

- hosts: rhev_h
  gather_facts: False

  tasks:
  - name : Subscribe RHEV_H
    get_url: url=http://172.27.1.1/repofiles/{{ item }} dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - rhel-7-server-rhev-mgmt-agent-rpms.repo

- hosts: osp_all
  gather_facts: False

  tasks:
  - name : Subscribe Openstack
    get_url: url=http://172.27.1.1/repofiles/{{ item }} dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - rhel-7-server-openstack-8-director-rpms.repo
    - rhel-7-server-openstack-8-optools-rpms.repo
    - rhel-7-server-openstack-8-rpms.repo
    - rhel-7-server-openstack-8-tools-rpms.repo

- hosts: ceph_all
  gather_facts: False

  tasks:
  - name : Subscribe Ceph
    get_url: url=http://172.27.1.1/repofiles/{{ item }} dest=/etc/yum.repos.d/{{ item }}
    with_items:
    - rhel-7-server-rhceph-1.3-calamari-rpms.repo
    - rhel-7-server-rhceph-1.3-installer-rpms.repo
    - rhel-7-server-rhceph-1.3-mon-rpms.repo
    - rhel-7-server-rhceph-1.3-osd-rpms.repo
    - rhel-7-server-rhceph-1.3-tools-rpms.repo

#Satellite is missing
